server:
  http_listen_port: 3200
  http_listen_address: 0.0.0.0

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: C:/tempo/traces

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  compaction:
    compaction_window: 2h

querier:
  search:
    query_timeout: 30s
