auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
common:
  path_prefix: C:\d

ingester:
  wal:
    enabled: true
    dir: C:\d\w
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 1m

schema_config:
  configs:
    - from: "2024-09-09"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: C:\d\t\i
    cache_location: C:\d\t\c
  filesystem:
    directory: C:\d\t

limits_config:
  allow_structured_metadata: true

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
