global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:

scrape_configs:
  - job_name: "applications"
    static_configs:
      - targets: ["otel-collector:28888"]
      
  - job_name: "otel-collector-internal"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
      
storage:
  tsdb:
    out_of_order_time_window: "30m"
